config/routes.rb
Rails.application.routes.draw do
  root to: 'industries#index'
  resources :industries do
    resources :businesses, except: [:index]
  end
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :industry
  validates :name, :presence => true
  validates :address, :presence => true
  validates :phone, :presence => true
end

app/models/industry.rb
class Industry < ActiveRecord::Base
  has_many :businesses
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  def new
    @industry = Industry.find(params[:industry_id])
    @business = @industry.businesses.new
  end

  def create
    @industry = Industry.find(params[:industry_id])
    @business = @industry.businesses.new(business_params)
    if @business.save
      redirect_to industry_path(@business.industry)
    else
      render :new
    end
  end

  def show
    @industry = Industry.find(params[:industry_id])
    @business = Business.find(params[:id])
  end

  def edit
    @industry = Industry.find(params[:industry_id])
    @business = Business.find(params[:id])
  end

  def update
    @business = Business.find(params[:id])
    @industry = Industry.find(params[:industry_id])
    if @business.update(business_params)
      redirect_to industry_business_path(@industry, @business)
    else
      render :edit
    end
  end

  private
  def business_params
    params.require(:business).permit(:name, :address, :phone)
  end

end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  def index
    @industries = Industry.order(:name)
    render :index
  end

  def show
    @industry = Industry.find(params[:id])
    render :show
  end

  def new
    @industry = Industry.new
  end

  def create
    @industry = Industry.new(industry_params)
    if @industry.save
      redirect_to industries_path
    else
      render :new
    end
  end

  def edit
    @industry = Industry.find(params[:id])
  end

  def update
    @industry = Industry.find(params[:id])
    if @industry.update(industry_params)
      redirect_to industries_path
    else
      render :edit
    end
  end

  def destroy
    @industry = Industry.find(params[:id])
    @industry.destroy
    redirect_to industries_path
  end


  private
  def industry_params
    params.require(:industry).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/_form.html.erb
<%= render "layouts/errors", :object => @business %>

<%= form_for [@industry, @business] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :address %>
  <%= f.text_field :address %><br>
  <%= f.label :phone %>
  <%= f.text_field :phone %><br>
  <%= f.submit class: "btn btn-success" %><br>
<% end %>

app/views/businesses/edit.html.erb
<h1>Edit Business</h1>

<%= render "form" %>

app/views/businesses/new.html.erb
<h1>Create a new business:</h1>

<%= render 'form' %>

app/views/businesses/show.html.erb
<h1><%= @business.name %></h1>

Address: &nbsp&nbsp
<%= @business.address %>
<br><br>
Phone: &nbsp&nbsp
<%= @business.phone %>

<%= link_to "Edit #{@business.name}", edit_industry_business_path %>

app/views/industries/_form.html.erb
<%= render "layouts/errors", :object => @industry %>

<%= form_for @industry do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/industries/edit.html.erb
<h1>Edit Industry</h1>

<%= render "form" %>

app/views/industries/index.html.erb
<h1>Index of Industry Types</h1>

<% if @industries.any? %>
  <ul>
    <% @industries.each do |industry| %>
      <li><%= link_to industry.name, industry_path(industry) %></li>
    <% end %>
  </ul>
<% else %>
  <p><h3>No Industries Currently in Index</h3></p>
<% end %>


<%= link_to 'Add a New Industry', new_industry_path %>

app/views/industries/new.html.erb
<h1>New Industry</h1>

<%= render "form" %>

app/views/industries/show.html.erb
<h3><%= @industry.name %></h3>

<%= link_to "Edit #{@industry.name}", edit_industry_path(@industry) %><br>
<%= link_to "Delete #{@industry.name}", industry_path(@industry),
                                  :data => {:confirm => "Confirm?",
                                  :method => "delete"} %>

<%if @industry.businesses.any? %>
  <h3>Businesses in this Industry:</h3>

  <table class="table table-striped">
    <thead>
      <tr>
        <th width='200px'>Business Name:</th>
        <th>Phone Number:</th>
      </tr>
    </thead>
    <tbody>
      <% @industry.businesses.each do |business| %>
        <tr>

          <td><%= link_to business.name, industry_business_path(@industry,business)%></td>
          <td><%= business.phone %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3>There are no businesses in this category yet.</h3>
<% end %>

<br>
<p><%= link_to "Add Business", new_industry_business_path(@industry) %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>These errors need fixed:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><% message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yellow Pages Clone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default navbar-fixed-top">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", industries_path %></li>
        <li><%= link_to "Add Industry", new_industry_path %></li>
      </ul>
    </nav>
    <%= yield %>
  </div>
</body>
</html>